name: build
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target: [ linux.amd64, linux.arm64, windows.amd64 ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: yarn
          cache-dependency-path: ui/yarn.lock
      - name: ui
        run: make ui
      - name: build
        env:
          target: ${{ matrix.target }}
        run: |
          os=$(echo $target | awk -F. '{print $1}')
          arch=$(echo $target | awk -F. '{print $2}')
          make build BUILD_OS="$os" BUILD_ARCH="$arch"
